language: generic
node_js:
  - "14.15.1"
ruby:
  - "2.5.7"

stages:
  - build_api
  - build_client
  - test_api
  - test_client

jobs:
  - stage: build_client
  - cache: 
    - npm
    - yarn
  - script:
    - docker build -t client ./client
    - docker run client yarn run build

  - stage: test_client
  - cache:
    - npm
    - yarn
  - before_script:
    - docker build -t client ./client
    - docker run client yarn run build

  - script:
    - docker run client yarn run test:unit

  - stage: build_api
  - cache: 
    - bundler
    - yarn
  - services:
    - postgresql
  - before_install:
    - nvm install --lts
  - script:
    - docker-compose -f api/docker-compose.yml up --build -d
    - docker-compose -f api/docker-compose.yml run web rake db:create
    - docker-compose -f api/docker-compose.yml run web rake db:migrate