language: generic
node_js:
  - "14.15.1"
ruby:
  - "2.5.7"

stages:
  - build_api
  - build_client
  - test_api
  - test_client

jobs:
  - stage: build_client
  - cache: 
    - npm
    - yarn
  - script:
    - docker build -t client ./client
    - docker run -p 8080:8080 client ./client

  - stage: build_api
  - cache: 
    - bundler
    - yarn
  - services:
    - postgresql
  - before_install:
    - nvm install --lts
  - script:
    - sudo docker-compose -f api/docker-compose.yml up --build