version: "3"

services:
  web:
    build: .
    volumes:
      - .:/api
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password